name: "build"

on:
  workflow_dispatch:
    inputs: {}

jobs:
  build:
    name: "build"
    runs-on: "ubuntu-latest"
    timeout-minutes: 25
    steps:
      - uses: "actions/checkout@v2"
      - run: "echo \"COMMIT_SHA=$(echo $GITHUB_SHA | cut -c 1-6)\" >> $GITHUB_ENV"
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: "buildbox"
        uses: "docker/setup-buildx-action@v1"
      - name: "docker push"
        env:
          REPOSITORY: "piotrjaromin/ecs-go"
          IMAGE_TAG: "${{ github.sha }}"
        run: |
          docker build -t $REPOSITORY:${{ env.COMMIT_SHA }} .
          docker push $REPOSITORY:${{ env.COMMIT_SHA }}
